/
  students/
     glenn/
        .gitbook.yaml
        README.md
        SUMMARY.md
     diana/
        .gitbook.yaml
        README.md
        SUMMARY.md
     christina/
        .gitbook.yaml
        README.md
        SUMMARY.md
     kathir/
        .gitbook.yaml
        README.md
        SUMMARY.md
     justin/
        .gitbook.yaml
        README.md
        SUMMARY.md
     afra/
        .gitbook.yaml
        README.md
        SUMMARY.md
     yoana/
        .gitbook.yaml
        README.md
        SUMMARY.md
     jinsu/
        .gitbook.yaml
        README.md
        SUMMARY.md
     tom/
        .gitbook.yaml
        README.md
        SUMMARY.md
     felicitas/
        .gitbook.yaml
        README.md
        SUMMARY.md
     caleb/
        .gitbook.yaml
        README.md
        SUMMARY.md
     alexia/
        .gitbook.yaml
        README.md
        SUMMARY.md
     rachel/
        .gitbook.yaml
        README.md
        SUMMARY.md
     antonia/
        README.md
        SUMMARY.md
     fernand/
        .gitbook.yaml
        README.md
        SUMMARY.md
     nils/
        .gitbook.yaml
        README.md
        SUMMARY.md
     prahad/
        .gitbook.yaml
        README.md
        SUMMARY.md
     mercedes/
        .gitbook.yaml
        README.md
        SUMMARY.md
     markus/
        .gitbook.yaml
        README.md
        SUMMARY.md
     felix/
        .gitbook.yaml
        README.md
        SUMMARY.md
     joshua/
        .gitbook.yaml
        README.md
        SUMMARY.md
