/
  students/
     glenn/
        README.md
        SUMMARY.md
     diana/        
        README.md
        SUMMARY.md
     christina/        
        README.md
        SUMMARY.md
     kathir/        
        README.md
        SUMMARY.md
     justin/        
        README.md
        SUMMARY.md
     afra/        
        README.md
        SUMMARY.md
     yoana/        
        README.md
        SUMMARY.md
     jinsu/        
        README.md
        SUMMARY.md
     tom/        
        README.md
        SUMMARY.md
     felicitas/        
        README.md
        SUMMARY.md
     caleb/        
        README.md
        SUMMARY.md
     alexia/        
        README.md
        SUMMARY.md
     rachel/        
        README.md
        SUMMARY.md
     antonia/
        README.md
        SUMMARY.md
     fernand/        
        README.md
        SUMMARY.md
     nils/        
        README.md
        SUMMARY.md
     prahad/        
        README.md
        SUMMARY.md
     mercedes/        
        README.md
        SUMMARY.md
     markus/        
        README.md
        SUMMARY.md
     felix/        
        README.md
        SUMMARY.md
     joshua/        
        README.md
        SUMMARY.md
